### ISSUE TITLE
有上传文件到服务器的示例吗?

### ISSUE THREAD

**Issue by CodeLYQ** [MeteorChina/MeteorDemo#2]
看过了你们 "移动设备 - 阿里云 Aliyun OSS示例程序"的示例代码,很赞!
我想请教一下:怎么上传的服务器(app的服务器),比如上传到 http://example.com/upload. 
服务端的JS代码该怎么写? 该怎么接收移动设备提交上传的文件?用collectionFS吗?
用cordova的 FileTransfer .upload 
 ft.upload(fileURI, encodeURI("http://example.com/upload"), win, fail, options);
试了,没成功! 期待解答!

**Comment by CodeLYQ** [comment]
已经解决了,thx.

**Comment by laosb** [comment]
Closing.
